### PR TITLE
add missing dependencies

### PR DESCRIPTION
**Pull request by albertlieyingadrian**
Screenshot 2022-09-08 at 10 02 14 AM
Mis
Screenshot 2022-09-08 at 10 02 33 AM
Add missing dependencies when running the server (`npm run dev`)

### CODE REVIEW

**Comment by babldev** [comment]
nmm what version of node are you running? i'm not seeing this

**Comment by albertlieyingadrian** [comment]
@babldev 
```
➜   npm -v
6.14.17
➜  node -v
v14.20.0
```

**Comment by albertlieyingadrian** [comment]
It didn't happen when I changed to node 18.x. will close this PR @babldev

**Comment by babldev** [comment]
Awesome, I'll update docs to indicate node 18. Thanks!

**Pull request closed without merging**
